### ISSUE TITLE
GoldenWall bug 

### ISSUE THREAD

**Issue by eladyaniv01** [eladyaniv01/SC2MapAnalysis#10]
Traceback (most recent call last):
  File "C:\Starcraft 2 botti\Ladder\Bots\Jensiiibot\sc2\main.py", line 174, in _play_game_ai
    await ai.on_step(iteration)
  File "C:\Starcraft 2 botti\Ladder\Bots\Jensiiibot\Jensiiibot.py", line 606, in on_step
    self.map_data = MapData(self)
  File "C:\Starcraft 2 botti\Ladder\Bots\Jensiiibot\MapAnalyzer\MapData.py", line 40, in __init__
    self.compile_map()  # this is called on init, but allowed to be called again every step
  File "C:\Starcraft 2 botti\Ladder\Bots\Jensiiibot\MapAnalyzer\MapData.py", line 182, in compile_map
    self._calc_chokes()
  File "C:\Starcraft 2 botti\Ladder\Bots\Jensiiibot\MapAnalyzer\MapData.py", line 157, in _calc_chokes
    region.region_chokes.append(new_choke)
AttributeError: 'NoneType' object has no attribute 'region_chokes'

**Comment by eladyaniv01** [comment]
seemse the algo for region detection is failing on this map,  need to investigate
![myplot](https://user-images.githubusercontent.com/40754127/87234254-effde400-c3d7-11ea-99b9-af7fbf296452.png)

**Comment by eladyaniv01** [comment]
fixed
