### ISSUE TITLE
DeathAuraLE bug

### ISSUE THREAD

**Issue by Jensiii666** [eladyaniv01/SC2MapAnalysis#12]
Traceback (most recent call last):
  File "/home/aiarena/aiarena-client/arenaclient/bots/Jensiiibot/sc2/main.py", line 174, in _play_game_ai
    await ai.on_step(iteration)
  File "/home/aiarena/aiarena-client/arenaclient/bots/Jensiiibot/Jensiiibot.py", line 606, in on_step
    self.map_data = MapData(self)
  File "/home/aiarena/aiarena-client/arenaclient/bots/Jensiiibot/MapAnalyzer/MapData.py", line 40, in __init__
    self.compile_map()  # this is called on init, but allowed to be called again every step
  File "/home/aiarena/aiarena-client/arenaclient/bots/Jensiiibot/MapAnalyzer/MapData.py", line 179, in compile_map
    self._calc_grid()
  File "/home/aiarena/aiarena-client/arenaclient/bots/Jensiiibot/MapAnalyzer/MapData.py", line 106, in _calc_grid
    vision_blockers_array[vision_blockers_indices] = 1
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by eladyaniv01** [comment]
fixed
